### ISSUE TITLE
Can you please provide more information

### ISSUE THREAD

**Issue by rakeshpalivela** [mjwheatley/cordova-plugin-android-fingerprint-auth#1]
Hi, I need some more information about this plugin. Like, do we need to add any libraries for this? Compatible with which Android devices..?  etc.

**Comment by mjwheatley** [comment]
This plugin uses the [Android 6.0 APIs](https://developer.android.com/about/versions/marshmallow/android-6.0.html) made available in SDK 23.  You need to set your targetSdkVersion and compileSdkVersion to 23 and use buildToolsVersion 23.0.2

This plugin is compatible with devices running Android 6.0 and above that have a hardware fingerprint scanner.  You should call `FingerprintAuth.isAvailable(isAvailableSuccess, isAvailableError);` to check if the plugin is available before trying to show the fingerprint authentication dialog.

I recommend using the [cordova-plugin-device](https://github.com/apache/cordova-plugin-device) and wrapping the isAvailable() call inside a conditional to check the platform and version.
```
if (device.platform === "Android" && device.version.startsWith("6.")) {
    FingerprintAuth.isAvailable(isAvailableSuccess, isAvailableError);
}
```

**Comment by rakeshpalivela** [comment]
@mjwheatley   Thanks for your reply. The above information will help me to configure.
