### ISSUE TITLE
Hardware not detected in Vivo V3 max

### ISSUE THREAD

**Issue by yogendrakarekar** [mjwheatley/cordova-plugin-android-fingerprint-auth#101]
I am using this plugin and the the application does not detects the hardwares and give "isHardwareAvailabe" as false, even when the fingerprint sensors are available.

Kindly help.

**Comment by mjwheatley** [comment]
Has a fingerprint been registered?  Is it a Samsung device that does not support the API (see the readme)?

**Comment by mjwheatley** [comment]
Closing because no response.
