### ISSUE TITLE
Enroll user fingerprint

### ISSUE THREAD

**Issue by renanrosalojasmm** [mjwheatley/cordova-plugin-android-fingerprint-auth#103]
Hello everyone,

Is there a way to enroll user's fingerprints?
I need to enroll the fingerprint and then store it. Is that possible?

**Comment by mjwheatley** [comment]
This is not possible with the Android Fingerprint API.  

You would need to attach a hardware peripheral to the device or use a touchless fingerprint sdk that utilizes the rear facing device camera, such as [ONYX from Diamond Fortress Technologies, Inc.](http://www.diamondfortress.com)  ONYX is not free. 

Disclaimer:  I work for Diamond Fortress

**Comment by renanrosalojasmm** [comment]
Thanks for your answer @mjwheatley !

Is there a way to scan the user fingerprint and transform it in a hash or something like that?

**Comment by mjwheatley** [comment]
No, that is currently not possible.  The closest I've come to that type of solution is an OAuth2 provider that authenticates the fingerprint in the cloud and returns an account I'd.  It is called (PassPrint)[https://www.passprint.me] and is currently functioning in a closed Beta.  It will be billed on a per user per month basis.  We are in need of some Beta integrators. If interested let me know and I can make arrangements.  You would integrate it in your app similar to using Google+ or Facebook.  It requires users to create a PassPrint account and use the PassPrint authenticator app to enroll and authenticate a fingerprint.
