### ISSUE TITLE
Why is encrypted token always changing?

### ISSUE THREAD

**Issue by livefrugally** [mjwheatley/cordova-plugin-android-fingerprint-auth#105]
please answer..

**Comment by mjwheatley** [comment]
Why are you calling encrypt multiple times?  You should call it once, store the token and then use decrypt.

**Comment by livefrugally** [comment]
I want to select the stored token from my database to decrypt it. but it is always changed when I encrypt my password.  I can't make select sql because the values had been changed when I touched fingerprint. Does it make sense to you?
