### ISSUE TITLE
Implementing FaceID iphoneX like feature in Android using this plugin

### ISSUE THREAD

**Issue by Abbiee** [mjwheatley/cordova-plugin-android-fingerprint-auth#108]
Hi,
Is there any way to implement the FaceID like feature in iPhoneX in my android device using this plugin. I mean i want to use the Trusted Face feature for my android application using Cordova. Please do tell . Any help will be appreciated along with ideas for Cordova.

**Comment by mjwheatley** [comment]
Could not find that an API exists to utilize Trusted Face feature.  If one does exist it would be better to integrate this feature in a separate plugin.  Closing as this does not pertain to this plugin.
