### ISSUE TITLE
Values for a_very_secret_encryption_key. Example?

### ISSUE THREAD

**Issue by malwatte** [mjwheatley/cordova-plugin-android-fingerprint-auth#11]
Hi,
Iam still not sure what to use for the a_very_secret_encryption_key ?
```
FingerprintAuth.show({
                    clientId: "myAppName",
                    clientSecret: "a_very_secret_encryption_key"
                }, successCallback, errorCallback);
```

I saw a similar question.
Appreciate if anyone can provide an example.
Thanks

**Comment by amjadajmer** [comment]
You can use a random string in clientSecret for eg:
FingerprintAuth.show({
                    clientId: "myAppName",
                    clientSecret: "Example"+Date.now()
                }, successCallback, errorCallback);

**Comment by mjwheatley** [comment]
The clientSecret is arbitrary, so it can be anything you want it to be.  It is only used as a seed to help generate a random encrypted token.  The plugin does not return the same encrypted token so it can not be used to identify a user.  It only ascertains that the user has enrolled a fingerprint on the device. @amjadajmer's example would suffice.
