### ISSUE TITLE
isAvailable() succeeds but it returns `false` on Google Pixel 2 (Android 8)

### ISSUE THREAD

**Issue by Muzietto** [mjwheatley/cordova-plugin-android-fingerprint-auth#115]
I am using plugin version 1.4.0.
My test phone is a fresh Google Pixel 2 with Android 8 and SDK level 27. I could not find the specific fingerprint API version, but it could be greater than 6.

The initial call to `isAvailable(cbs, cbf)` succeeds, but it returns `false`.

Is this plugin able to support fingerprint API versions >6?

**Comment by mjwheatley** [comment]
The Android Fingerprint API has not changed since 6.0 to my knowledge.
Please report the entire result object.  Also check `isHardwaredDetected` and `hasEnrolledFingerprints`

Perhaps if it is a fresh Google Pixel 2, you have not enrolled any fingerprints yet?

**Comment by Muzietto** [comment]
Yes, there we no fingerprints. Gotta check `hasEnrolledFingerprints` first.
Thank you very much.
