### ISSUE TITLE
Re:Permission denied alert coming while using cordova-plugin-android-fingerprint-auth

### ISSUE THREAD

**Issue by Arunraj93** [mjwheatley/cordova-plugin-android-fingerprint-auth#122]
the error coming as permission denied how i solve this issue

**Comment by mjwheatley** [comment]
Make sure the `USE_FINGERPRINT` permission is specified in the `AndroidManifest.xml`
This line should have been added by the plugin, but if not make sure to copy it there.
```
<uses-permission android:name="android.permission.USE_FINGERPRINT" />
```
