### ISSUE TITLE
Usage within Ionic View on Samsung S7 Edge

### ISSUE THREAD

**Issue by Fritz1971** [mjwheatley/cordova-plugin-android-fingerprint-auth#13]
Hi, 

I am using the plugin but it is not working for me. I am using S7 Edge with Android 6.0.1 and Ionic View to test the authentication. 

Regards
Matthias

**Comment by mjwheatley** [comment]
What exactly is not working? Are you seeing any error messages in your LogCat?  What framework are you using, Ionic, Ionic2, or Cordova?  Is the FingerprintAuth global variable defined?  Is the isAvailable() method or the show() method not work?

**Comment by Fritz1971** [comment]
Hi, thank you for answering. I am not at the office for a couple of days. I have seen that I did not wait for the device ready event to fire so most probably this is the problem. I will close this file for now and reopen it in the case that the issue remains. 
Thanks
