### ISSUE TITLE
Handling failed authentication

### ISSUE THREAD

**Issue by Gregen11** [mjwheatley/cordova-plugin-android-fingerprint-auth#14]
Is there a way to handle failed authentications (i.e. fingerprint/pin didn't match)

My use case would be to track the number of times a fingerprint has failed and after x attempts, cancel the dialog.

The other issue occurring out of this is that after x number of failed fingerprint attempts, it goes to the device's pin (or whatever your device has as a backup for your fingerprint).

I already have a built in pin page on the app I'm working on. Having it switch to the device's pin page rather than canceling the dialog to show the app's pin page would be confusing. (As they may have a different pin for their device and for their app)

If you'd like me to clarify more or add in more examples of what I'm looking for, let me know.

Thanks!

**Comment by mjwheatley** [comment]
I don't know if this is consistent across all device manufacturers, but the max number of attempts is 5 failed attempts.  When this happens an error is thrown and onError() gets called. From there I am triggering the authentication screen regardless of the disableBackup parameter.

I could modify this to check the disableBackup parameter and if it is disabled I could fail back to the calling application.  

There is also an onAuthenticationFailed() method in the FingerprintUiHelper class.  I could create a parameter to set the number of attempts to less than 5 and track the failed attempts in the onAuthenticationFailed() method.  I could then fail over to the authentication screen or back to the application depending on the disableBackup parameter.

How many failed attempts were you wanting to allow?

**Comment by Gregen11** [comment]
Checking disableBackup in onError() would definitely work.
Also adding another parameter along the lines of numAttempts could be useful. 

5 attempts works fine for me. Mostly, being able to handle what happens in my application when onError() is called and disableBackup is true would be useful. (e.g. canceling the dialog, going to a different page, logging out a user, etc.)

Thank you for your response and your time!

**Comment by mjwheatley** [comment]
published v0.0.13 to address this issue.
Plugin now returns error `"Too many attempts. Try again later."` if `disableBackup` is set to `true`.
Also added parameter `maxAttempts` to set number of failed attempts to fewer than 5 attempts.

**Comment by Gregen11** [comment]
I just tested that out and it works great.

Thanks!
