### ISSUE TITLE
Multi-access

### ISSUE THREAD

**Issue by tmwebs** [mjwheatley/cordova-plugin-android-fingerprint-auth#144]
I have a question, can it be configured so that different users can access it with different fingers?

I have an APP that accesses with user and password, and I try to have several different users use the same device and can log in with the fingerprint to make it faster.

I'm trying to associate a user and password with a finger.

Thank you.

**Comment by mjwheatley** [comment]
This is not possible with the Android Fingerprint Manager.

**Comment by tmwebs** [comment]
Do you know any way to do that? 
Thank you

**Comment by mjwheatley** [comment]
The Android Fingerprint Manager does not return a fingerprint ID or anything like that.  Only if it matches one of the enrolled fingerprints on the device.  You could at a minimum prompt for the username that you want to log into, but then one user could log in as another on the same device.  Good for a family but probably not what you are looking for.  There are a couple solutions out there but not free.  I have attempted to create an OAuth2 platform but have not been able to commercialize it and get it mainstream.  If you're curious you can have a look at https://www.passprint.me
