### ISSUE TITLE
BAD_PADDING_EXCEPTION after reinstall

### ISSUE THREAD

**Issue by AlibekJ** [mjwheatley/cordova-plugin-android-fingerprint-auth#146]
So, I encrypt with certain username-password:
```javascript
FingerprintAuth.encrypt({
  clientId: "something",
  username: "username",
  password: "password"
})
```
Decrypting works fine:
```javascript
FingerprintAuth.decrypt({
  clientId: "something",
  username: "username",
  token: "encrypted string"
})
```
Then I uninstall the app, install again, all the app data gets restored from google drive by the OS, cordova reports the same UUID, everything works as if the app was never uninstalled, except decrypting does does not work and throws **BAD_PADDING_EXCEPTION**.

I am supplying the very same data into the .decrypt method, yet it fails. 
Any ideas?

**Comment by mjwheatley** [comment]
My guess is that the cipher that was stored in the keystore was not backed up and you would need to re-encrypt to regenerate a new cipher to be saved to the keystore.

**Comment by AlibekJ** [comment]
What should I save? 
Would saving IV solve the problem you think?

**Comment by AlibekJ** [comment]
Answering my own question: storing they key components outside of the keystore solves this particular problem. However, as I realized after reflecting on the solution a bit, this defeats the whole purpose of using the secure, hardware-assisted keystore.
