### ISSUE TITLE
A question about multiple users

### ISSUE THREAD

**Issue by Shpresim** [mjwheatley/cordova-plugin-android-fingerprint-auth#147]
Hi. Great plugin so far! 
Wanted to ask you a question about the possibility of logging in to an application which has many users. The users are using the same device (one OS account but multiple fingerprints), and use the password/username combination to login. Is it possible to incorporate the fingerprint like this, and if yes how:
1. Enter login information (password/username) first time (storing in Local Storage of tokens)
2. After logging out he enters the username and presses the fingerprint (or just fingerprint??) he gets logged in.

So the issue is _identifying_ the fingerprints of a user, and check if it has already been logged in.
Saw similar discussions on the issues but couldn't make it work. Would appreciate any help!

**Comment by mjwheatley** [comment]
What you describe is possible for a single user device.  The problem is that any registered fingerprint on the device can pass the authentication challenge.  Android Fingerprint Manager does not provide information about which fingerprint was matched.  So this will not work the way you want for a multi-user device.

**Comment by mjwheatley** [comment]
You would need to have a fingerprint AFIS for enrolling and subsequent validation against the enrolled fingerprint.  I have built such systems while employed by a company selling such technology.  If interested you may research the company.  Diamondfortress.com

**Comment by Shpresim** [comment]
Thanks for helping. Will definitely do some research about that.
