### ISSUE TITLE
Backup validation has fingerprint too

### ISSUE THREAD

**Issue by malwatte** [mjwheatley/cordova-plugin-android-fingerprint-auth#17]
When I add a new fingerprint Plugin shows the backup validation (not regular fingerprint dialog). But the problem is it has fingerprint option too. That means I can use fingerprint as the backup validation when fingerprint are changed.

Please refer the screenshot.
![backup validation](https://cloud.githubusercontent.com/assets/2534778/18743126/3b50bef4-80d5-11e6-8f20-35c717203eb2.jpg)

Is it possible to ignore fingerprint changes and show fingerprint dialog as normal?
Or would it be possible to show only the PIN or passcode in backup validation?

Device: HTC 10
Version: 6.0.1

Thank you.

**Comment by mjwheatley** [comment]
There is not a way to disable the fingerprint authentication on the backup credentials screen.

I have published v0.1.0 to include a `userAuthRequired` parameter that you can set to `false` to ignore fingerprint changes and show the fingerprint dialog as normal.

**Comment by malwatte** [comment]
Greatly appreciate your quick response.  Thank you.
