### ISSUE TITLE
How to change texts in Fingerprint dialog

### ISSUE THREAD

**Issue by malwatte** [mjwheatley/cordova-plugin-android-fingerprint-auth#18]
How to change texts in Fingerprint dialog (e.g. "Confirm fingerprint to continue")?
Can we set custom text when authenticating using FingerprintAuth.show() ?
Thank you.

**Comment by mjwheatley** [comment]
I would have to create a parameter for each text field.
Please send me a list of all the text fields that you would like to be able to customize.

These would override the language parameter so you would have to translate and set the parameters if you want to display a different language that is not supported.

**Comment by mjwheatley** [comment]
published v0.2.0 to add parameters to set the text for the title, message, and hint.

**Comment by malwatte** [comment]
@mjwheatley ,
Greatly appreciate your quick response.  Thank you.
