### ISSUE TITLE
Fingerprint Scanner Dialogue Box 

### ISSUE THREAD

**Issue by rushabh138** [mjwheatley/cordova-plugin-android-fingerprint-auth#19]
We are using samsung device with android version 6. Fingerprint is available. However, when isAvailabeSuccess method is called, we are not getting fingerprint scan dialogue box to validate fingerprint and login into app. Also, result.isAvailable is true. 

For testing purpose, we are using clientId: "AppName" and clientSecret: "123456789". 

How should we get this fixed and get fingerprint scan dialogue box?

`function isAvailableSuccess(result) {
    alert("FingerprintAuth available: " + JSON.stringify(result) + "Result: " + result.isAvailable);
    if (result.isAvailable) {
        FingerprintAuth.show({
            clientId: "CargoTrak",
            clientSecret: "123456789" ,
        }, successCallback, errorCallback);
    }
}`

**Comment by mjwheatley** [comment]
Please run your application in Android Studio, look at the logcat, and report any error messages.

**Comment by mjwheatley** [comment]
@rushabh138 were you able to get the dialog to show up?

**Comment by rushabh138** [comment]
Yes.. I forget to declare callback function after isAvailableSuccess is true. I thought it is handle by plugin. It fixed once I declare success and error callback function. Appreciate your support. 

Please inform me when you come up with new updates for fingerprint plugin.

Thanks.

**Comment by mjwheatley** [comment]
I think you can Star and watch this repository at the top of the page and GitHub will automatically send you a notification when I make changes to the repo.

Glad you were able to get it working.

**Comment by rushabh138** [comment]
I am testing plugin on Android device with version 6 i.e. SDK 23. However, fingerprint auth is not working. I did setup fingerprint on device and it works for other app i.e. Bank of America; but it doesn't show up touch ID box on the app using fingerprint-auth plugin. 

Attach with this message is device info for your reference. The logcat error is false for everything. Can you please provide reason or fix for this error.

Thanks. 

![device ingo](https://cloud.githubusercontent.com/assets/7264453/18790038/43f1eea6-817b-11e6-917f-d101755cb314.JPG)

**Comment by mjwheatley** [comment]
Please check and make sure you have the required permission in the AndroidManifest.xml
<uses-permission android:name="android.permission.USE_FINGERPRINT" />

**Comment by rushabh138** [comment]
Thanks for a response.

Can you please provide me with detail permission required for it to work?

**Comment by mjwheatley** [comment]
Sorry, I copied and pasted but forgot to put it in a code block.
```
<uses-permission android:name="android.permission.USE_FINGERPRINT" />
```

Also, I just remembered another user mentioned in issue #8 that the Samsung GS5 does not support the Google Fingerprint API

Also here http://stackoverflow.com/questions/35353472/will-samsung-support-googles-fingerprint-api-from-marshmallow

The S6 and S7 do support the Google Fingerprint API.

This plugin does not and will not support the Samsung Pass SDK.

**Comment by rushabh138** [comment]
Does this plugin supports range of device types like Samsung, HTC, Motorola? Do you know any generic fingerprint plugin which works on majority of android device family? Because cordova-fingerprint-auth works only with new samsung phone i.e. S6 and S7. It doesn't work on older phone. Perhaps, I didn't get chance to test of other devices like HTC or motorola.

**Comment by mjwheatley** [comment]
It should work on any device that uses Android 6.0 (sdk 23) and supports the Google Fingerprint API. Older phones most likely do not have hardware fingerprint scanners.  If the OEM of the device does not enable the Google Fingerprint API, this plugin will not work for that device.

Here is a list of phones with hardware fingerprint scanners: http://us.phonegg.com/list/182-Cell-Phones-with-Fingerprint-Scanner

**Comment by rushabh138** [comment]
What is OEM of the device? Can we get the status of OEM in our app?
