### ISSUE TITLE
Ng-cordova

### ISSUE THREAD

**Issue by jupegarnica** [mjwheatley/cordova-plugin-android-fingerprint-auth#2]
Hi there!

First of all,  great job man.  There are lots of people waiting for this :)

There is any plan to port this to ng-cordova?  I could be great to make it work in a easy way with ionic or a stand alone angular app.

Thank you

**Comment by mjwheatley** [comment]
Shouldn't be all that difficult to manage.  Ng-cordova is managed by the folks over at @driftyco.  You would need to petition them to adopt this plugin into their framework.
