### ISSUE TITLE
Parameter maxAttempts does not work properly

### ISSUE THREAD

**Issue by eKazim** [mjwheatley/cordova-plugin-android-fingerprint-auth#23]
For example i call function `FingerprintAuth.show` with `maxAttempts = 3`. Then i failed all attempts. After error message about too many attempts, dialog was closed. And this is fine.
But after i called this function the second time with the same parameters, then i receive the same message after only 2 failed attempts. I guess this happens because there are exists some system counter in Android, that ingores our custom counter.

**Comment by mjwheatley** [comment]
Yes, that is correct, the default implementationi is 5 attempts and then blocks for 30 seconds.  The maxAttempts parameter was requested for a custom implementation.  If you want to shorten the number of requests, you will need to implement the blocking and delay in your own code.

**Comment by eKazim** [comment]
Ok, thanks for your support!
