### ISSUE TITLE
Translate not work for 'zh' and 'fr'

### ISSUE THREAD

**Issue by adelannucci** [mjwheatley/cordova-plugin-android-fingerprint-auth#28]
Hello Matthew Wheatley.

I am using the plugin however when I change the language to French or Chines it does not alter the strings. Only Spanish and English this ok

``` 
var params = {
          clientId: deviceUtils.ANDROID_FINGERPRINT_ID,
          clientSecret: clientSecret,
          locale: 'fr'
        };

FingerprintAuth.show(params, vm.sucess vm.error);
```

I do not know if I'm doing something wrong?

**Comment by mjwheatley** [comment]
Try uninstalling and reinstalling the plugin to ensure that the new language string resources get copied from the plugin into your application.

Your params look correct.

**Comment by adelannucci** [comment]
Worked, thank you.
Now another question.
You intend to add support for Portuguese and Japanese?

**Comment by mjwheatley** [comment]
I am relying on other developers from other countries to contribute translations in their native language.  I'm happy to receive pull requests to add other languages.

**Comment by adelannucci** [comment]
I can do the translation to Portuguese, I have the file fpauth-strings. That's enough?

**Comment by mjwheatley** [comment]
Yes, that would be enough.  Please clone the repository.  Create a new directory /res/android/values-pt and put the translated fpauth-strings.xml in this directory.  Then send me a pull request (PR) and I will update the plugin.xml and README.

**Comment by adelannucci** [comment]
Ok, Thanks :)
