### ISSUE TITLE
When Passing ClientId and ClientSecret empty the fingerPrint Access worked ? 

### ISSUE THREAD

**Issue by iosdroid** [mjwheatley/cordova-plugin-android-fingerprint-auth#29]
I am using this plugin for finger print authentication when i pass the params clientid and client secret as empty that time also its recognize the finger print. Then what is the purpose of client id and client secret

**Comment by mjwheatley** [comment]
I am only checking that the parameters are present, not that they contain a value.  The plugin will still work if they are empty.  The clientId is used as the alias for the keystore to store the secret key that is generated.  The client secret is used to create the encrypted token that is returned.  Currently it doesn't have much value / use.  It was just part of the Android demo that I used to create the plugin.
