### ISSUE TITLE
clientId and clientSecret information ?

### ISSUE THREAD

**Issue by sdkcarlos** [mjwheatley/cordova-plugin-android-fingerprint-auth#3]
Hi, thanks for take the time to write a plugin for this android feature !

I would like to know specifically which values should have the clientId and clientSecret parameters.

```javascript
FingerprintAuth.show({
      clientId: "My Super App",// or is the package instead ???? : com.mycompany.mysuperapp
      clientSecret: "a_very_secret_encryption_key" // how do i get a client secret?
}, successCallback, errorCallback);
```

I'm searching on the google documentation but it is not clear to me. Can i set any value for clientId and clientSecret ?.

I mean with a random secret id it is working, but this is the best practice? I would really appreciate if you give me info about this.

Thanks !

**Comment by mjwheatley** [comment]
Your welcome!  I'm glad to find that the plugin is being used and is helpful to others.
You are correct about the clientId and clientSecret, those values are set by the developer to be specific for their application.  The clientId is the alias for your application's use of the keystore via this plugin.  The clientSecret is used to create an encrypted token that is returned upon successful fingerprint validation.  You may use a different clientSecret per user.  I would suggest concatenating a static clientSecret with a userId to generate a unique token that can be used to identify and authenticate a user.

**Comment by sdkcarlos** [comment]
Perfect, thanks for your support !
