### ISSUE TITLE
Support for Japanese translation

### ISSUE THREAD

**Issue by worzella** [mjwheatley/cordova-plugin-android-fingerprint-auth#30]
In our use of your excellent app, our test team discovered that Japanese is not one of your supported translation languages. Is this correct and if so, do you have plans to add. We do have translation services available and might be able to provide the string translations....

**Comment by mjwheatley** [comment]
As this is an open source plugin, I am relying on developers from other countries to contribute translations in their native language. I'm happy to receive pull requests to add other languages. Please clone the repository. Create a new directory /res/android/values-jp and put the translated fpauth-strings.xml in this directory. Then send me a pull request (PR) and I will update the plugin.xml and README.

**Comment by mjwheatley** [comment]
Added to v0.3.4
