### ISSUE TITLE
Not working in IBM MobileFirst/Worklight android application

### ISSUE THREAD

**Issue by swamy470** [mjwheatley/cordova-plugin-android-fingerprint-auth#33]
HI

I have added this fingerprint authentication plugin in my worklight application,But i am getting below errors in logcat. Please let me know what need to be done to solve this issue

11-14 11:12:47.671: W/PluginManager(30565): THREAD WARNING: exec() call to FingerprintAuth.authenticate blocked the main thread for 33ms. Plugin should use CordovaInterface.getThreadPool().
11-14 11:12:47.671: D/FingerprintAuth(30565):  mFragment = new FingerprintAuthenticationDialogFragment()
11-14 11:12:47.692: D/FingerprintAuth(30565):  insdie initCipher()
11-14 11:12:47.712: D/FingerprintAuthDialog(30565): disableBackup: false
11-14 11:12:47.713: W/ResourceType(30565): No package identifier when getting value for resource number 0x00000000
11-14 11:12:47.713: D/AndroidRuntime(30565): Shutting down VM
11-14 11:12:47.716: E/AndroidRuntime(30565): FATAL EXCEPTION: main
11-14 11:12:47.716: E/AndroidRuntime(30565): Process: com.fingerPrint, PID: 30565
11-14 11:12:47.716: E/AndroidRuntime(30565): android.content.res.Resources$NotFoundException: Resource ID #0x0
11-14 11:12:47.716: E/AndroidRuntime(30565): 	at android.content.res.Resources.getValue(Resources.java:1351)
11-14 11:12:47.716: E/AndroidRuntime(30565): 	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2777)
11-14 11:12:47.716: E/AndroidRuntime(30565): 	at android.content.res.Resources.getLayout(Resources.java:1165)
11-14 11:12:47.716: E/AndroidRuntime(30565): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:421)
11-14 11:12:47.716: E/AndroidRuntime(30565): 	at com.fingerPrint.FingerprintAuthenticationDialogFragment.onCreateView(FingerprintAuthenticationDialogFragment.java:87)
11-14 11:12:47.716: E/AndroidRuntime(30565): 	at android.app.Fragment.performCreateView(Fragment.java:2220)
11-14 11:12:47.716: E/AndroidRuntime(30565): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:973)
11-14 11:12:47.716: E/AndroidRuntime(30565): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
11-14 11:12:47.716: E/AndroidRuntime(30565): 	at android.app.BackStackRecord.run(BackStackRecord.java:793)
11-14 11:12:47.716: E/AndroidRuntime(30565): 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1537)
11-14 11:12:47.716: E/AndroidRuntime(30565): 	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:482)
11-14 11:12:47.716: E/AndroidRuntime(30565): 	at android.os.Handler.handleCallback(Handler.java:746)
11-14 11:12:47.716: E/AndroidRuntime(30565): 	at android.os.Handler.dispatchMessage(Handler.java:95)
11-14 11:12:47.716: E/AndroidRuntime(30565): 	at android.os.Looper.loop(Looper.java:148)
11-14 11:12:47.716: E/AndroidRuntime(30565): 	at android.app.ActivityThread.main(ActivityThread.java:5443)
11-14 11:12:47.716: E/AndroidRuntime(30565): 	at java.lang.reflect.Method.invoke(Native Method)
11-14 11:12:47.716: E/AndroidRuntime(30565): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
11-14 11:12:47.716: E/AndroidRuntime(30565): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
11-14 11:12:47.718: E/com.worklight.common.Logger$UncaughtExceptionHandler(30565): Logger$UncaughtExceptionHandler.uncaughtException in Logger.java:471 :: Uncaught Exception
11-14 11:12:47.718: E/com.worklight.common.Logger$UncaughtExceptionHandler(30565): android.content.res.Resources$NotFoundException: Resource ID #0x0
11-14 11:12:47.718: E/com.worklight.common.Logger$UncaughtExceptionHandler(30565): 	at android.content.res.Resources.getValue(Resources.java:1351)
11-14 11:12:47.718: E/com.worklight.common.Logger$UncaughtExceptionHandler(30565): 	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2777)
11-14 11:12:47.718: E/com.worklight.common.Logger$UncaughtExceptionHandler(30565): 	at android.content.res.Resources.getLayout(Resources.java:1165)
11-14 11:12:47.718: E/com.worklight.common.Logger$UncaughtExceptionHandler(30565): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:421)
11-14 11:12:47.718: E/com.worklight.common.Logger$UncaughtExceptionHandler(30565): 	at com.fingerPrint.FingerprintAuthenticationDialogFragment.onCreateView(FingerprintAuthenticationDialogFragment.java:87)
11-14 11:12:47.718: E/com.worklight.common.Logger$UncaughtExceptionHandler(30565): 	at android.app.Fragment.performCreateView(Fragment.java:2220)
11-14 11:12:47.718: E/com.worklight.common.Logger$UncaughtExceptionHandler(30565): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:973)
11-14 11:12:47.718: E/com.worklight.common.Logger$UncaughtExceptionHandler(30565): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
11-14 11:12:47.718: E/com.worklight.common.Logger$UncaughtExceptionHandler(30565): 	at android.app.BackStackRecord.run(BackStackRecord.java:793)
11-14 11:12:47.718: E/com.worklight.common.Logger$UncaughtExceptionHandler(30565): 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1537)
11-14 11:12:47.718: E/com.worklight.common.Logger$UncaughtExceptionHandler(30565): 	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:482)
11-14 11:12:47.718: E/com.worklight.common.Logger$UncaughtExceptionHandler(30565): 	at android.os.Handler.handleCallback(Handler.java:746)
11-14 11:12:47.718: E/com.worklight.common.Logger$UncaughtExceptionHandler(30565): 	at android.os.Handler.dispatchMessage(Handler.java:95)
11-14 11:12:47.718: E/com.worklight.common.Logger$UncaughtExceptionHandler(30565): 	at android.os.Looper.loop(Looper.java:148)
11-14 11:12:47.718: E/com.worklight.common.Logger$UncaughtExceptionHandler(30565): 	at android.app.ActivityThread.main(ActivityThread.java:5443)
11-14 11:12:47.718: E/com.worklight.common.Logger$UncaughtExceptionHandler(30565): 	at java.lang.reflect.Method.invoke(Native Method)
11-14 11:12:47.718: E/com.worklight.common.Logger$UncaughtExceptionHandler(30565): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
11-14 11:12:47.718: E/com.worklight.common.Logger$UncaughtExceptionHandler(30565): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
11-14 11:12:47.723: D/com.worklight.wlclient.api.WLLifecycleHelper(30565): WLLifecycleHelper.logAppSession in WLLifecycleHelper.java:109 :: Tried to record an app crash without a starting timestamp

**Comment by mjwheatley** [comment]
Make sure all the plugin resources from /res/android get copied to the appropriate directories in your Android application.
