### ISSUE TITLE
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by jskrepnek** [mjwheatley/cordova-plugin-android-fingerprint-auth#46]
Hi,

Plugin is crashing when the power button is pressed and the fingerprint fragment is displayed.  It's treating this as an error (' Fingerprint operation canceled.') and then trying to dismiss the fragment, but it appears that dismissing is not valid at that point.

Relevant guidance:
http://www.androiddesignpatterns.com/2013/08/fragment-transaction-commit-state-loss.html

Android: 7.1.1
Plugin: 1.2.2

```
01-09 13:03:16.808 26489 26489 E AndroidRuntime: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
01-09 13:03:16.808 26489 26489 E AndroidRuntime:        at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1434)
01-09 13:03:16.808 26489 26489 E AndroidRuntime:        at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1452)
01-09 13:03:16.808 26489 26489 E AndroidRuntime:        at android.app.BackStackRecord.commitInternal(BackStackRecord.java:708)
01-09 13:03:16.808 26489 26489 E AndroidRuntime:        at android.app.BackStackRecord.commit(BackStackRecord.java:672)
01-09 13:03:16.808 26489 26489 E AndroidRuntime:        at android.app.DialogFragment.dismissInternal(DialogFragment.java:301)
01-09 13:03:16.808 26489 26489 E AndroidRuntime:        at android.app.DialogFragment.dismiss(DialogFragment.java:267)
01-09 13:03:16.808 26489 26489 E AndroidRuntime:        at com.cordova.plugin.android.fingerprintauth.FingerprintAuthenticationDialogFragment.onError(FingerprintAuthenticationDialogFragment.java:271)
01-09 13:03:16.808 26489 26489 E AndroidRuntime:        at com.cordova.plugin.android.fingerprintauth.FingerprintUiHelper$1.run(FingerprintUiHelper.java:113)
01-09 13:03:16.808 26489 26489 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
01-09 13:03:16.808 26489 26489 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
01-09 13:03:16.808 26489 26489 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
01-09 13:03:16.808 26489 26489 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6119)
01-09 13:03:16.808 26489 26489 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method) 01-09 13:03:16.808 26489 26489 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
01-09 13:03:16.808 26489 26489 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by mjwheatley** [comment]
Are you touching the fingerprint sensor at the same time as the bower button?
Home button or power button?

From your stack trace it looks like somehow onAuthenticationError() is being triggered.

Are you hitting the home button (which also has a fingerprint sensor) and the application is going into the background?  

This sounds like it is the case.  You are touching the fingerprint sensor which is causing onAuthenticationError() to be called while the application is going into the background.  Then the postDelay() function is being called to dismiss the dialog.

Reference: http://stackoverflow.com/questions/9325238/proper-way-of-dismissing-dialogfragment-while-application-is-in-background

Looks like we might need to change all the `dismiss()` calls to `dismissAllowingStateLoss()` in `FingerprintAuthenticationDialogFragment.java`

Give that a try and if it works you can send me a pull request.

**Comment by jskrepnek** [comment]
Thanks @mjwheatley.

No, not touching fingerprint sensor at the same time, nor does the device I've reproduced this on have a home button with a sensor.  Definitely only touching power button.  

From what I recall, the 'system cancelled' scenario was triggering onAuthenticationError.

Given this, does it still make sense to attempt the change you're suggesting?

In any case, I'll give it a try and see.

**Comment by mjwheatley** [comment]
Yes, despite whatever is triggering the call to onAuthenticatioinError(), the proposed change should hopefully remedy the problem.
