### ISSUE TITLE
FingerprintAuth.isAvailable is returning isAvailable: false, isHardwareDetected: false, hasEnrolledFingerprints: false

### ISSUE THREAD

**Issue by Spandanagithub** [mjwheatley/cordova-plugin-android-fingerprint-auth#50]
Using samsung Galaxy s5 and I do have registered fingerprint in my device.

Please provide any solution for this.

**Comment by mjwheatley** [comment]
Samsung Galaxy s5 does not implement the Android Fingerprint API used by this plugin.
