### ISSUE TITLE
TypeError: FingerprintAuth.show is not a function

### ISSUE THREAD

**Issue by zjx** [mjwheatley/cordova-plugin-android-fingerprint-auth#53]
Hi Buddy,

I am trying to use this plugin in an ionic 1 project, but encounter below problem when running on android devices:

"Error in Success callbackId: FingerprintAuth1038847942 : 
TypeError: FingerprintAuth.show is not a function", source: file:///android_asset/www/cordova.js (312)
chromium: [INFO:CONSOLE(309)] "Uncaught (in promise) TypeError: FingerprintAuth.show is not a function"

Here is my Code:

`                    if (typeof FingerprintAuth != 'undefined') {

                        console.log('FingerprintAuth Ready');

                        var client_id = "Your client ID";
                        var client_secret = "A very secret client secret (once per device)";

                        FingerprintAuth.isAvailable(function(result) {
                            if (result.isAvailable) {
                                console.log('Fingerprint Device Available');
                                if(result.hasEnrolledFingerprints) {

                                    alert('Fingerprint hasEnrolledFingerprints');

                                    FingerprintAuth.show({
                                        clientId: client_id,
                                        clientSecret: client_secret
                                    }, function (result) {
                                        if (result.withFingerprint) {
                                            alert("Successfully authenticated using a fingerprint");
                                        } else if (result.withPassword) {
                                            alert("Authenticated with backup password");
                                        }
                                    }, function(error) {
                                        console.log(error); // "Fingerprint authentication not available"
                                    });
                                }else{
                                    alert("Fingerprint auth available, but no fingerprint registered on the device");
                                }
                            } else {
                              console.log('Fingerprint Device Not Available');
                            }
                        }, function(message) {
                            alert("Cannot detect fingerprint device : "+ message);
                        });

                    } else {
                      console.log('FingerprintAuth Not Ready');
                    }
`

**Comment by zjx** [comment]
sorry guys, looks like I referenced some outdated examples. after checked the documents I notices the show function was removed.. we should use encrypt or decrypt function. by the way, what is the difference of these 2 functions? I can use anyone of them to authenticate the user, right?

**Comment by mjwheatley** [comment]
See the "How to use" section of the README.

If you just want to authenticate you should use encrypt().

encrypt() will take the username and password and return an encrypted token.

decrypt() will take the encrypted token and return the decrypted password
