### ISSUE TITLE
BadPaddingException:  javax.crypto.AEADBadTagException

### ISSUE THREAD

**Issue by ganjahnavarro** [mjwheatley/cordova-plugin-android-fingerprint-auth#55]
Hi,

I'm testing a bare sample of this plugin, I just want to ask what to ask if I'm missing something because I'm getting an error of BadPaddingException:  javax.crypto.AEADBadTagException, error callback of encrypt is called. 

I'm sure fingerprint is available: {"isAvailable":true,"isHardwareDetected":true,"hasEnrolledFingerprints":true}

This is my config:

var encryptConfig = {
    clientId: "com.phonegap.sample.Sample",
    username: "currentUser",
    password: "currentUserPassword"
};

and I called it with FingerprintAuth.encrypt(encryptConfig, encryptSuccessCallback, encryptErrorCallback); 

encryptErrorCallback is called after dialog is showed and I successfully scanned my fingerprint. I'm using a rooted xiaomi 3s  if it's any help.

Thanks

**Comment by yoprogramo** [comment]
The same for a Xiaomi 5 with Miui 7. Did you solve the problem?

**Comment by harshvardhan12** [comment]
Did you checked in devices other than Xiaomi ? i was also having the problem with Xiaomi phones but when i checked in other devices i was not getting this error. not sure what is the issue here.

**Comment by yoprogramo** [comment]
In fact in my Mi5 does not happend, I suppose it is the Android version (or MIUI one) more than the device itself.

**Comment by harshvardhan12** [comment]
Hi wheatley,
please provide your suggestion on this as i am also having the same problem. If you say i will explain you the senerio what is happening in my case

**Comment by mjwheatley** [comment]
From your comments so far it sounds like it may be device specific.  Without steps to consistently repeat this issue it would be very difficult to debug.  Yes, please describe your issue in more detail.

I have received a bad padding exception, not sure if it is exactly the same or not, after removing fingerprints from the device and adding them back.  I had to verify using the backup credentials before I could use fingerprint authentication again.

**Comment by harshvardhan12** [comment]
yes, correct that is the exact senerio which you describe in your second paragraph

**Comment by yoprogramo** [comment]
My case is the exact scenario as @ganjahnavarro in the first message.

**Comment by mjwheatley** [comment]
Closing this issue. Please reopen the issue if it is still a problem.

**Comment by vvarda** [comment]
Have similar issue, with multiple users (user_1, user_2):
1. Encrypt user_1 credentials:
```
const encryptConfig = {
    clientId: <com.sample.sample>,
    username: <user_1>,
    password: <user_1_password>
};

FingerprintAuth.encrypt(encryptConfig, ...)
```

2. Encrypt user_2 credentials:
```
const encryptConfig = {
    clientId: <com.sample.sample>,
    username: <user_2>,
    password: <user_2_password>
};

FingerprintAuth.encrypt(encryptConfig, ...)
```

3. Decrypt works **fine** for both of them (user_1, user_2):

user_1
```
const decryptConfig = {
    clientId:  <com.sample.sample>,
    username: <user_1>,
    token: <user_1_token>
};

FingerprintAuth.decrypt(decryptConfig, ...)
```
user_2
```
const decryptConfig = {
    clientId:  <com.sample.sample>,
    username: <user_2>,
    token: <user_2_token>
};

FingerprintAuth.decrypt(decryptConfig, ...)
```

**BUT..**

4. Delete any of user's cipher (user_1 or user_2):
```
const deleteConfig = {
    clientId:  <com.sample.sample>,
    username: <user_1>
};

FingerprintAuth.delete(deleteConfig,  ...)
```

5. Trying to decrypt user_2 credentials
```
const decryptConfig = {
    clientId:  <com.sample.sample>,
    username: <user_2>,
    token: <user_2_token>
};

FingerprintAuth.decrypt(decryptConfig, ...)
```

6. Error received
`E/FingerprintAuth: Failed to encrypt the data with the generated key: BadPaddingException:  javax.crypto.BadPaddingException`
