### ISSUE TITLE
Finger Print Device is not detected

### ISSUE THREAD

**Issue by roylabanon** [mjwheatley/cordova-plugin-android-fingerprint-auth#60]
Hi Guys,

Would like to seek help on using this plugin, when i call the function 

> FingerprintAuth.isAvailable

 it returns

> Object {isAvailable: false, isHardwareDetected: false, hasEnrolledFingerprints: false} 

I am using Cordova and Samsung S5, my screenlock is fingerprint enabled also, anything i missed? tia!

**Comment by mjwheatley** [comment]
Samsung does not support the Android Fingerprint API on all of their devices.  Unfortunately the S5 is one that does not.
