### ISSUE TITLE
Unable to install with existing build-extras.gradle

### ISSUE THREAD

**Issue by RYFN** [mjwheatley/cordova-plugin-android-fingerprint-auth#62]
My cordova project already contains a `build-extras.gradle` file. When I `cordova plugin add cordova-plugin-android-fingerprint-auth` it results in the following error:

```
Fetching plugin "cordova-plugin-android-fingerprint-auth" via npm
Installing "cordova-plugin-android-fingerprint-auth" for android
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-android-fingerprint-auth':Error: Uh oh!
"/Users/me/Documents/Projects/project-name/platforms/android/build-extras.gradle" already exists!
```

I've had to manually remove my existing build-extras.gradle file, then merge in the contents for this plugin - is this something that could be handled automatically?

**Comment by mjwheatley** [comment]
`build-extras.gradle` was removed from plugin as of version 1.2.8
