### ISSUE TITLE
isAvailable all results false

### ISSUE THREAD

**Issue by zapphyre** [mjwheatley/cordova-plugin-android-fingerprint-auth#67]
I have Samsung Galaxy S5 and my issue is that `isAvailableSuccess()` always results in 3x false through I have fingerprints set up on my device and using them for unlock. I run Ionic debug build as `ionic run android -lsc` Do I need some special permission for this?
Thanks

**Comment by mjwheatley** [comment]
I have addressed this in the README under the About section.

<----
This plugin will only work on devices whose manufacturers have implemented the Android 6.0 Fingerprint Authentication API. This plugin does not support the Samsung Pass SDK and not all Samsung devices implement the Android 6.0 Fingerprint Authentication API. If you are testing this plugin on a Samsung device and it is not working, please check the device compatibility before reporting an issue.
---->
