### ISSUE TITLE
Unable to build for minSdkVersion < 21

### ISSUE THREAD

**Issue by kunal999** [mjwheatley/cordova-plugin-android-fingerprint-auth#73]
Does this plugin allow to build with minSdkVersion < 21?
It gives me an error:-
invalid resource directory name: <project>\platforms\android\build\intermediates\res\merged\debug/drawable-anydpi-v21

However bumping the minSdkVersion to 21 in the AndroidManifest.xml file allows me to build fine.

Is this plugin compatible with Support Library v4? (As in this answer - http://stackoverflow.com/a/36788905/846727 ?)

**Comment by mjwheatley** [comment]
This plugin is not using support library v4.
