### ISSUE TITLE
Error FINGERPRINT_DATA_NOT_DELETED

### ISSUE THREAD

**Issue by WuglyakBolgoink** [mjwheatley/cordova-plugin-android-fingerprint-auth#78]
If no data was saved and I try to call second time delete() I got exception FINGERPRINT_DATA_NOT_DELETED.

https://github.com/mjwheatley/cordova-plugin-android-fingerprint-auth/blob/master/src/android/FingerprintAuth.java#L351-L371

In my case this is no error... 

Can I ignore this error?

**Comment by mjwheatley** [comment]
You are probably receiving that exception because there was no data found to be deleted.  

Yes, you would be fine to ignore the exception and proceed.

**Comment by WuglyakBolgoink** [comment]
Hallo @mjwheatley 

In which case I can get this Exception?

**Comment by mjwheatley** [comment]
The one you said you were receiving.
