### ISSUE TITLE
Does the plugin works with third party Fingerprint device

### ISSUE THREAD

**Issue by golevaibhav** [mjwheatley/cordova-plugin-android-fingerprint-auth#82]
I need to create an Android App where user will scan his fingerprint from third party Fingerprint reader. Does this plugin works with other than inbuilt fingerprint sensors?  
Please help me with this.
Thank you.

**Comment by mjwheatley** [comment]
No, this plugin only works with the Android Fingerprint API.

So users will scan their fingerprint using a third party scanner and you need an Android app to capture a fingerprint and match against that print?  Where is the fingerprint data stored? Sounds like you need server side matching.  Do you need matching algorithms?

It is not a free solution, but I recommend you look into ONYX from (Diamond Fortress Technologies)[http://www.diamondfortress.com]. It can provide image capture and matching algorithms (by Innovatrics) if needed.  The image capture and processing can be customized to match against third party scanner.
Disclaimer: I am a shareholder in the company.
