### ISSUE TITLE
How are the following strings controlled?

### ISSUE THREAD

**Issue by RYFN** [mjwheatley/cordova-plugin-android-fingerprint-auth#83]
How are the following messages controlled?

* Make sure that your finger covers the entire Home key
* Keep your finger on the Home key a little longer

They appear when you use the fingerprint button incorrectly. I can't see them in any of the values.xml files, does this message come directly from the OS itself?

We're seeing the above messages being displayed in english, even when the device language is set to french.

**Comment by mjwheatley** [comment]
They are passed in by the Fingerprint API.

In FingerpirntUiHelper.java:

```
@Override
    public void onAuthenticationHelp(int helpMsgId, CharSequence helpString) {
        showError(helpString);
    }
```

The 2 arguments received by onAuthenticationHelp() are set by the Fingerprint API.  Not sure why the resources are not being translated if both the plugin language and device language are set to French.  Perhaps there is not a device translation for that string?

However, the onAuthenticatioinHelp() method would allow for identifying the helpMsgId and providing a translated string contained in the plugin's fpauth-strings.xml.

**Comment by RYFN** [comment]
Thanks, that's very helpful - I think there's probably something odd going on with this particular user's device.
