### ISSUE TITLE
Getting Error After Updating API to use Version 1.3.0

### ISSUE THREAD

**Issue by ankitNyuCS** [mjwheatley/cordova-plugin-android-fingerprint-auth#86]
build       19-Jun-2017 00:05:09        [INF] [shellscript] :mergeDebugAssets
build       19-Jun-2017 00:05:09        [INF] [shellscript] :generateDebugResValues
build       19-Jun-2017 00:05:09        [INF] [shellscript] :generateDebugResources
build       19-Jun-2017 00:05:11        [INF] [shellscript] :mergeDebugResources
build       19-Jun-2017 00:05:11        [INF] [shellscript] :processDebugManifest
build       19-Jun-2017 00:05:12        [INF] [shellscript] :processDebugResources
build       19-Jun-2017 00:05:12        [INF] [shellscript] :generateDebugSources
build       19-Jun-2017 00:05:12        [INF] [shellscript] /u01/MacAgent/xml-data/build-dir/XXXXXXXXXXXXXXXXXX/cordova/platforms/android/src/com/cordova/plugin/android/fingerprintauth/FingerprintAuth.java:597: error: variable cryptoObject might not have been initialized
build       19-Jun-2017 00:05:12        [INF] [shellscript]             if (cryptoObject == null) '{'
build       19-Jun-2017 00:05:12        [INF] [shellscript]                 ^
build       19-Jun-2017 00:05:12        [INF] [shellscript] Note: Some input files use or override a deprecated API.
build       19-Jun-2017 00:05:12        [INF] [shellscript] Note: Recompile with -Xlint:deprecation for details.
build       19-Jun-2017 00:05:12        [INF] [shellscript] Note: Some input files use unchecked or unsafe operations.
build       19-Jun-2017 00:05:12        [INF] [shellscript] Note: Recompile with -Xlint:unchecked for details.
build       19-Jun-2017 00:05:12        [INF] [shellscript] 1 error
build       19-Jun-2017 00:05:12        [INF] [shellscript]
build       19-Jun-2017 00:05:12        [INF] [shellscript] FAILURE: Build failed with an exception.
build       19-Jun-2017 00:05:12        [INF] [shellscript]
build       19-Jun-2017 00:05:12        [INF] [shellscript] * What went wrong:
build       19-Jun-2017 00:05:12        [INF] [shellscript] Execution failed for task ''':compileDebugJavaWithJavac'''.
build       19-Jun-2017 00:05:12        [INF] [shellscript] > Compilation failed; see the compiler error output for details.
build       19-Jun-2017 00:05:12        [INF] [shellscript]
build       19-Jun-2017 00:05:12        [INF] [shellscript] * Try:
build       19-Jun-2017 00:05:12        [INF] [shellscript] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
build       19-Jun-2017 00:05:12        [INF] [shellscript] :compileDebugJavaWithJavac FAILED
build       19-Jun-2017 00:05:12        [INF] [shellscript]
build       19-Jun-2017 00:05:12        [INF] [shellscript] BUILD FAILED

**Comment by mjwheatley** [comment]
I have committed some unpublished changes in regards to initializing the cryptoObject.  Are you able clone the repo and build using the cloned directory?

**Comment by mjwheatley** [comment]
Does version 1.3.1 work for you?
