### ISSUE TITLE
plugin does not differs fingers

### ISSUE THREAD

**Issue by tperrelli** [mjwheatley/cordova-plugin-android-fingerprint-auth#90]
Hello all. I have fingers sabe on my smartphone.

I do encrypted one time for each finger using this options

clientId - both for same fingers
username - different for each finger

After this i've tried to use decrypt function changing my fingers with another password.
For example

What i've registered

finger1
pass 123

finger2
pass456

What i did is used decrypted as well using

finger1
pass456

or 
finger2
pass123

So whats is the utility of the token if the plugin does not differs each finger and those password or what i'm doing wrong?

Thanks

**Comment by mjwheatley** [comment]
Android Fingerprint API does not return a Fingerprint ID.  It only returns if the probe matched one of the prints registered on the device.  The encrypted token is for securely storing the user credentials and so you can retrieve the password for a standard login with username and password.

**Comment by mjwheatley** [comment]
Any fingerprint registered on the device can authorize decryption of the token.
