### ISSUE TITLE
Problem with Phonegap Build

### ISSUE THREAD

**Issue by aramgev** [mjwheatley/cordova-plugin-android-fingerprint-auth#91]
When I want to build application using your plugin with phonegap build cloud, I get the following error:

> Failed to install 'cordova-plugin-android-fingerprint-auth': CordovaError: Uh oh!
> "/project/res/values-it" already exists!
>     at copyNewFile (/project/cordova/lib/pluginHandlers.js:248:15)
>     at install (/project/cordova/lib/pluginHandlers.js:43:17)
>     at Object.process (/project/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
>     at PluginManager.doOperation (/project/cordova/node_modules/cordova-common/src/PluginManager.js:117:20)
>     at PluginManager.addPlugin (/project/cordova/node_modules/cordova-common/src/PluginManager.js:147:17)
>     at /project/cordova/Api.js:254:18
>     at _fulfilled (/project/cordova/node_modules/q/q.js:854:54)
>     at self.promiseDispatch.done (/project/cordova/node_modules/q/q.js:883:30)
>     at Promise.promise.promiseDispatch (/project/cordova/node_modules/q/q.js:816:13)
>     at /project/cordova/node_modules/q/q.js:570:49
> Uh oh!
> "/project/res/values-it" already exists!

I fork your plugin and remove all values-* from resourses, then it passes build

**Comment by mjwheatley** [comment]
Of you remove those resources you will not have any other languages available.  Please review comments from issues #68 and #61 and see if those are helpful.

**Comment by aramgev** [comment]
Thanks, for the answer, but they are not helpful. Actually, I don't need other languages and translation can be done client side
