### ISSUE TITLE
Backdrop color/opacity

### ISSUE THREAD

**Issue by JDonadio** [mjwheatley/cordova-plugin-android-fingerprint-auth#93]
Hi there,

There is a way to change the backdrop opacity and/or color? The idea is make it almost black so once displayed the modal you cannot see anything on the backdrop.

**Comment by mjwheatley** [comment]
No, there is not a way to control those features via the plugin.  You can achieve this with your own custom implementation and control when you open the authentication dialog.  For example, open a new page/view with only a black background to handle the authentication flow.
