### ISSUE TITLE
plugin compatibility issues with cordova android 7.0.0 

### ISSUE THREAD

**Issue by dickverweij** [mjwheatley/cordova-plugin-android-fingerprint-auth#98]
When I install this plugin to a freshly created cordova android 7.0.0 project I get the following issues when building my android apk:

C:\Users\XXXXX>ionic cordova build android
> cordova build android
cp: copyFileSync: could not write to dest file (code=ENOENT):C:\Users\XXXXX\platforms\android\res\xml\config.xml

It appears that the config.xml (and manifest) file location was changed.

Is there an easy fix?

**Comment by mjwheatley** [comment]
Published v1.4.1
@dickverweij please test the new version and report if it fixes this issue.
